#import "contrat_pedagogique_template.typ": *
#contrat_pedagogique(
  name : "Slodowska Currie",
  firstname : "Marie",
  address: "Pologne",
  email: "N/A",
  phone: "N/A",
  activity_type: "Recherche",
  country_town: "France, Paris",
  start_date: "3/11/1891",
  end_date: "4/07/1934",
  guardians: (
    (name: "Slodowska" ,
      firstname: "Bronisława",
      address: "Pologne",
      email: "N/A",
      phone: "N/A"
    ),
    (name: "Slodowska" ,
      firstname: "Władysław",
      address: "Pologne",
      email: "N/A",
      phone: "N/A"
    ),
  ),
  activities: ("Plein de choses", "et d'autres", "et d'autres", "et toujours plus"),
  acquis_list: (
    ("Maitriser la radioactivite : prix Nobel de physique « en reconnaissance de leurs services rendus, par leur recherche commune sur le phénomène des radiations découvert par le professeur Henri Becquerel"),
    ("Observer le polonium : prix Nobel de chimie lui est décerné, «en reconnaissance des services pour l’avancement de la chimie par la découverte de nouveaux éléments : le radium et le polonium, par l’étude de leur nature et de leurs composés»"),
    ("Conduire des voitures : participe à la conception de dix-huit unités chirurgicales mobiles, des « ambulances radiologiques » surnommées a posteriori les « petites Curies »"),
  ),
  project_code: "A travers l'Europe",
  organisation_envoi_name: "",
  organisation_envoi_address: "",
  organisation_envoi_email: "",
  organisation_envoi_phone: "",
  organisation_accueil_name: "",
  organisation_accueil_address: "",
  organisation_accueil_email: "",
  organisation_accueil_phone: "",
  qualification: "",
  school_year: "",
  european_qualification_framework: "",
  staff_qualification: "",
  staff_school_year: "",
  staff_european_qualification_framework: "",
  hosting_responsables: (
    (name: "",
    firstname: "",
    email: "",
    phone: "",
    responsabilities: ""),
  ),
  sending_responsables: (
    (name: "",
    firstname: "",
    email: "",
    phone: "",
    responsabilities: ""),
  ),
  companions : (
    (name: "",
    firstname: "",
    email: "",
    phone: "",
    responsabilities: ""),
  ),
)